apiVersion: v1
kind: Service

metadata:
  name: terragrunt-devops-project-service

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  selector:
    app: terragrunt-devops-project

  ports:
  - port: 80
    targetPort: 80

  type: LoadBalancer
